### ISSUE TITLE
bug(global - select browsers/devices): Stencil app disabled : shows developer instructions screen

### ISSUE THREAD

**Issue by LizCottrell** [openforge/OPENFORGE.IO#109]
**Environment**
Production 6-11-18

**Steps to Recreate:** 
Navigate to openforge.io on the following devices/browsers:
- Tablet (iPad mini, iOS 10.3.2) Safari + Chrome
- Desktop (macBook, macOS High Sierra 10.13.4) Firefox 59.0.2

**Expected Result:**
Display OpenForge website

**Actual Result:** 
Stencil app is disabled for select browsers and displays developer instructions

**ipadmini_ios10-3-2_chrome_06-11-18:**
![ipadmini_ios10-3-2_chrome_06-11-18](https://user-images.githubusercontent.com/12145554/41240771-47628bc8-6d69-11e8-891b-2bd6b4114e07.PNG)

**ipadmini_ios10-3-2_safari_06-11-18:**
![ipadmini_ios10-3-2_safari_06-11-18](https://user-images.githubusercontent.com/12145554/41240772-477dfa2a-6d69-11e8-8f9d-012cd16445d1.PNG)

**macbook_macos10-13-4_firefox59-0-2_06-11-18:**
<img width="700" alt="macbook_macos10-13-4_firefox59-0-2_06-11-18" src="https://user-images.githubusercontent.com/12145554/41240773-478c7744-6d69-11e8-81dd-cf53e58a302a.png">

**Comment by GeoTech7515** [comment]
Working as expected.
