### ISSUE TITLE
bug-UI(contact page - hero): “Request Now” button text is the wrong color

### ISSUE THREAD

**Issue by LizCottrell** [openforge/OPENFORGE.IO#110]
**Environment:**
Production 6-11-18

**Steps to Recreate:**
Navigate to openforge.io/contact on any device/browser

**Expected Result:**
Contact page hero CTA button text is white

**Actual Result:**
Contact page hero CTA button text is black

_________________________________
**Design:**
<img width="774" alt="design_contact_hero" src="https://user-images.githubusercontent.com/12145554/41241385-c7e60454-6d6a-11e8-916b-1e12f42a3a86.png">

**Production:**
<img width="815" alt="prod_contact_hero" src="https://user-images.githubusercontent.com/12145554/41241386-c828bd9e-6d6a-11e8-805c-0decd55d578b.png">

**Comment by LizCottrell** [comment]
@Wholloran - this is QA ready

**Comment by Wholloran** [comment]
button now matches the design closing the ticket
