### ISSUE TITLE
bug-UI(home page - meet the team): Employee profiles do not match design

### ISSUE THREAD

**Issue by LizCottrell** [openforge/OPENFORGE.IO#111]
**Environment:**
Production 6-11-18

**Steps to Recreate:**
Navigate to openforge.io/#about on any device/browser

**Expected Result:**
Employee profiles should mimic design (display round images and be a consistent/cohesive design on all viewport sizes)

**Actual Result:**
Employee profiles display square images (+ left-aligned on large viewports), are inconsistent heights at different viewport sizes, social buttons are too small and not centered (accessibility issue on mobile), etc. 

_________________________________
**Design:**
![design_home_employee-profiles](https://user-images.githubusercontent.com/12145554/41242884-c215a526-6d6e-11e8-9b01-c785e725424e.png)

**Production:**
XL viewport:
<img width="1439" alt="prod_home_employee-profiles-xl" src="https://user-images.githubusercontent.com/12145554/41242919-ddf88d4e-6d6e-11e8-9d40-1ce1380c5eec.png">
Mobile viewport:
<img width="327" alt="prod_home_employee-profiles_mobile" src="https://user-images.githubusercontent.com/12145554/41242920-de081e9e-6d6e-11e8-9a29-e4e86a6ea014.png">
Inconsistent heights:
<img width="720" alt="prod_home_employee-profiles" src="https://user-images.githubusercontent.com/12145554/41242925-e0ea9a56-6d6e-11e8-9ddf-0e6a67edd408.png">

:**

**Comment by Wholloran** [comment]
@PaulPaulDevelops  I see that Liz made this dev complete, Do you know if this is on a branch somewhere? I Don't see a PR for it and currently Develop doesn't reflect this

**Comment by Wholloran** [comment]
The Designs for this page have changed, So closing the Ticekt
