### ISSUE TITLE
bug-UI(contact page - hero): hero header text is cut off on mobile

### ISSUE THREAD

**Issue by LizCottrell** [openforge/OPENFORGE.IO#119]
**Environment:**
Production 6-15-18

**Steps to Recreate:**
Navigate to openforge.io/contact on a mobile device (< 350px wide)

**Expected Result:**
Text in hero space ("Let's Work Together") should wrap to 2 lines if overflow occurs (1 line of text longer than the screen-width).

**Actual Result:**
Text in hero space is cut off (displays: "Let's Work Toget").

_________________________________
**Production:**
Mobile viewport (iPhone 5):
![screen shot 2018-06-15 at 11 49 39 am](https://user-images.githubusercontent.com/12145554/41477548-a229707c-7092-11e8-9e06-da2c8c1bba22.png)

**Comment by LizCottrell** [comment]
@Wholloran - this is QA ready

**Comment by Wholloran** [comment]
The text is no longer Cut off so closing the ticket
