### ISSUE TITLE
chore (optimization): Image display dimensions should match natural aspect ratio.

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#127]
Attaching screenshot of lighthouse
<img width="891" alt="screen shot 2018-06-21 at 12 19 25 pm" src="https://user-images.githubusercontent.com/996175/41731913-a95c4c60-754d-11e8-977e-30d4d2b38e09.png">

**Comment by Wholloran** [comment]
Fixed!
