### ISSUE TITLE
bugfix(robots.txt):  robots.txt is not valid

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#128]
Let's fix our robots.txt, screenshot attached from lighthouse

NOTE:   Once fixed, get Jedi, Geoff, or Paulina to request our site be crawled by google.

<img width="886" alt="screen shot 2018-06-21 at 12 22 28 pm" src="https://user-images.githubusercontent.com/996175/41732233-86ee49ac-754e-11e8-99fc-f0ebb11d5e07.png">

**Comment by Wholloran** [comment]
Can be closed -paulina
