### ISSUE TITLE
"mailto:hello@openforge.io" tab opening in chrome when pressing buttons

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#13]
"mailto:hello@openforge.io" tab opening in Chrome browser when pressing the "Learn More" or "Get In Touch" buttons.

**Comment by Fdom92** [comment]
@Wholloran this still being an issue? Seems to be fixed in the current build

**Comment by Wholloran** [comment]
This is no longer happening with the button listed above so closing Ticket.
