### ISSUE TITLE
About Page: Background Image not loading

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#145]
When you navigate to the About tab the background image and Text does not load(See screenshot). 
This is present on all browsers. Please note if you refresh while on the about page or navigate to it via URL the image/text will load

Note WHile image/text is not showing if you zoom in or out it will display

<img width="1278" alt="screen shot 2018-07-10 at 12 21 50 pm" src="https://user-images.githubusercontent.com/37937571/42523537-fffe8ea0-843b-11e8-9d15-386fe4cd2951.png">

**Comment by GroveDev** [comment]
PR #153 fixes this

**Comment by Wholloran** [comment]
Working as expected, Closing Ticket
