### ISSUE TITLE
Multiple Pages: Links not opening in a new tab

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#146]
The following Links on the home page are not opening in a new tab:
- The Ionic Framework
- Angular (Google)
- React.js (Facebook)
- Node.js,
- MongoDB
- Adobe Photoshop
- Sketch App
- Abstract

The following Links on the Opportunities page are not opening in a new tab:
- “Ionic Team”
- “React App”
- “Ionic”

Present On all browsers

**Comment by GroveDev** [comment]
PR #153 fixes this

**Comment by Wholloran** [comment]
Working As expected. Closing TIcket.
