### ISSUE TITLE
About Page: The “Get in touch button” take you to the incorrect location

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#147]
About - The “get in touch button” doesn’t take you to the contacts page; It takes me to https://openforge-dev.firebaseapp.com/<<mailto:hello@openforge.io>> or opens native mail app if that is set up on the device

Present In all browsers

**Comment by GroveDev** [comment]
PR #153 fixes this.

**Comment by Wholloran** [comment]
Working as expected. Closing Ticket
