### ISSUE TITLE
Contact Us: Multiple emails 

### ISSUE THREAD

**Issue by GeoTech7515** [openforge/OPENFORGE.IO#148]
- When double clicking the send button on the contact page after filling out all fields, the corresponding email will be sent twice

- Also in the opportunities page as well

**Comment by GroveDev** [comment]
PR 157 fixes this. The submit button gets disabled while the form is being submitted.

**Comment by Wholloran** [comment]
After testing the submit button is not getting disabled after the first submit and you can still send multiple emails. So changing status to open.
