### ISSUE TITLE
twitter link for Luis leads to "Page doesn't exist"

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#15]
Twitter link for Luis leads "page doesn't exist". We might have the wrong URL for Luis account or he might not have a twitter anymore. if he doesn't I would recommend removing the twitter link form his account.

**Comment by Fdom92** [comment]
It seems to be a mistake, the twitter is `luiskcs89`

**Comment by Fdom92** [comment]
This issue is fixed in this PR https://github.com/openforge/OPENFORGE.IO/pull/80

**Comment by Wholloran** [comment]
There is no longer a twitter link for Luis so closing the Ticket.
