### ISSUE TITLE
Home page: App Development off center

### ISSUE THREAD

**Issue by GeoTech7515** [openforge/OPENFORGE.IO#150]
While in a smaller browser size the cards become off center.
![screen shot 2018-07-10 at 3 24 00 pm](https://user-images.githubusercontent.com/21181898/42532598-60ced0d2-8455-11e8-8a8b-3f103319cc98.png)

**Comment by Fdom92** [comment]
This https://github.com/openforge/OPENFORGE.IO/pull/166 fix this.
