### ISSUE TITLE
Opportunities page: Look into file size/ display message if file is to large

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#152]
When attaching a larger PDF the email will not be sent but is displayed to the user as being sent. Look into allowed file size on AWS S3 and what the maximum size is currently. Then create an error message to display to the user if they attach a file that's too large to be sent. Note: allow them to send the request without an attachment after the error is shown

**Comment by GroveDev** [comment]
PR 156 will fix this.
