### ISSUE TITLE
Add `rel="noopener"` or `rel="noreferrer" to external links

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#158]
per lastest lighthouse scan, our internal links don't have a "rel" property set for them.

![screen shot 2018-07-13 at 12 29 10 pm](https://user-images.githubusercontent.com/37937571/42702741-5f811ef2-8698-11e8-9ae5-5626d015168f.png)

**Comment by Fdom92** [comment]
This PR https://github.com/openforge/OPENFORGE.IO/pull/163 fix this

**Comment by Wholloran** [comment]
Issue fixed Closing
