### ISSUE TITLE
Enable Text Compression

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#160]
As per our latest lighthouse run, we need to enable text compression (here is the link from the screenshot for more info (https://developers.google.com/web/tools/lighthouse/audits/text-compression)

![screen shot 2018-07-13 at 12 34 10 pm](https://user-images.githubusercontent.com/37937571/42703026-3c01b60c-8699-11e8-92c8-0e7d0560246b.png)

**Comment by nbey** [comment]
This seems to have been resolved -- I'm not sure what the fix was, but this audit is currently passing on both dev and live instances.
