### ISSUE TITLE
Footer: Add "suit #301" to our address 

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#182]
Add "suit #301" to our address in the footer. It should read: 
OpenForge
1040 N 2nd Street, Suite 301
Philadelphia, PA 19123

is currently shows what is in the screenshot
![screen shot 2018-07-24 at 11 42 14 am](https://user-images.githubusercontent.com/37937571/43149919-aed5a436-8f36-11e8-9349-02c45b6e1a6f.png)

**Comment by jedihacks** [comment]
Pushed directly into dev

**Comment by Wholloran** [comment]
Suit #301 has been added, closing Defect
