### ISSUE TITLE
SafarI opportunities page (Dev)

### ISSUE THREAD

**Issue by GeoTech7515** [openforge/OPENFORGE.IO#189]
There is no "Scroll to learn More button" on the opportunities page on safari

**Comment by jedihacks** [comment]
I can't reproduce this - can someone verify or provide more information?  

Using safari version 11.1.2 (13605.3.8)

<img width="1512" alt="screen shot 2018-07-31 at 9 05 01 am" src="https://user-images.githubusercontent.com/996175/43461222-ee986102-94a0-11e8-9d1d-e73a4bcfe5c6.png">

**Comment by GeoTech7515** [comment]
Tested and works as expected. Closing Ticket
