### ISSUE TITLE
Contact Page: Double Options(Dev)

### ISSUE THREAD

**Issue by GeoTech7515** [openforge/OPENFORGE.IO#190]
There are two Unsure Options in the Budget section of the form
![screen shot 2018-07-30 at 5 09 20 pm](https://user-images.githubusercontent.com/21181898/43425321-40d60c20-9420-11e8-8df9-851a28aff3ff.png)

**Comment by jedihacks** [comment]
Fixed https://github.com/openforge/OPENFORGE.IO/commit/936f5a3f8c0d95379888594d6366da1233422919

**Comment by Wholloran** [comment]
Only one unsure option is being displayed, closing defect
