### ISSUE TITLE
Contact Page:  Phone number should support dashes

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#192]
We should support multiple phone number formats, such as "123-123-1234", "+1-123-234-1234", etc.

<img width="1446" alt="screen shot 2018-07-31 at 9 09 30 am" src="https://user-images.githubusercontent.com/996175/43461460-8b6bfb10-94a1-11e8-9a9d-f291e96dcf25.png">

**Comment by Wholloran** [comment]
form now supports dashes, closing ticket
