### ISSUE TITLE
Edge: Team Member Page

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#209]
The spacing Between the Team members on the about page is incorrect. There is no spacing between the photos in a collum. 

Edge Specific

**Comment by Fdom92** [comment]
@Wholloran i tried to reproduce this on the latest changes on dev environment but i'm not able to see this issue anymore, i can see space between columns and rows. Can you re test this?

**Comment by Wholloran** [comment]
@Fdom92 retested this and I'm still seeing the same issue. Note: that I'm testing this using the Dev url. 

<img width="1274" alt="screen shot 2018-09-03 at 3 33 31 pm" src="https://user-images.githubusercontent.com/37937571/44999941-e65ef600-af8e-11e8-9b00-60b81c58c156.png">

**Comment by Fdom92** [comment]
@Wholloran i tried to reproduce this but i'm not able to reproduce that, this is my result on edge on the dev site url:

<img width="961" alt="screen shot 2018-09-18 at 11 34 24" src="https://user-images.githubusercontent.com/7361737/45679797-a759a480-bb39-11e8-9469-a550d70ac279.png">

<img width="961" alt="screen shot 2018-09-18 at 11 35 25" src="https://user-images.githubusercontent.com/7361737/45679672-66619000-bb39-11e8-9ca7-6b2bda78cbe9.png">

<img width="961" alt="screen shot 2018-09-18 at 11 35 52" src="https://user-images.githubusercontent.com/7361737/45679802-ac1e5880-bb39-11e8-88bf-fa0f6ef2c0b3.png">

I was able to resize without problems, this is my edge version:

```
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
```

**Comment by Wholloran** [comment]
looks like this issue is limited to the edge version 41.162...  working correctly on higher versions. THis is an acceptable use case. Closing ticket
