### ISSUE TITLE
Service Pages: Header image load time

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#227]
The header image on the services pages take a few seconds to load the first time and display a gray background. If there anything we can change to have them match the speed of the header images on the other pages.

Steps to recreate:
navigate to the site for fresh session
go to the services page
header image takes a few seconds to load the first time

**Comment by Fdom92** [comment]
@Wholloran i think we can speed up this header images on the services pages making some compression on those images.

The header img for app development is 3.6MB
The header img for app design is 1.4MB
The header img for consulting is 1.1MB

**Comment by Wholloran** [comment]
As fer mentioned above this ties in with open issue #184  so closing this ticket
