### ISSUE TITLE
Homepage: Safari Only, Redirect to service not working

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#234]
While on safari, when you click on DEV/UI/Consulting card you are not redirected to the corresponding services page. 

NOTE: that if you test on mobile it won't redirect no matter what the browser, this is intentional as we don't have mobile designs yet.

**Comment by Fdom92** [comment]
@Wholloran tried to reproduce this in safari with latest changes in dev environment with out results, can you re check this?

**Comment by Wholloran** [comment]
The redirect seems to be working now, Closing ticket
