### ISSUE TITLE
Services Page: Extra spacing on the right side of the services page

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#236]
When you navigate to any service page, the page is scrollable left to right because there is extra white space on the Righthand side of the page. This is on all browsers and all screen sizes.

**Comment by Fdom92** [comment]
@Wholloran can you provide a screenshot of this? I'm not able to see the extra spacing at the right at all screens, only to the smaller ones and due to the footer button, this is what you mean?

**Comment by Wholloran** [comment]
<img width="1280" alt="screen shot 2018-08-30 at 8 49 02 am" src="https://user-images.githubusercontent.com/37937571/44852608-ad8eec00-ac31-11e8-9caa-896af3ab9087.png">

If you go to any services page, on any size desktop or browser and scroll to the right you will see this extra spacing. it seems like the page it self-doesn't match the nav bar width

**Comment by Wholloran** [comment]
No longer Any extra space, Closing ticket
