### ISSUE TITLE
"Learn more" Button on About Page

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#26]
Pressing the "Learn more" Button on About Page will snap rather than scroll, on Chrome, Edge, and IE

**Comment by daftclaud** [comment]
Please provide browser versions used to test.

**Comment by Fdom92** [comment]
@Wholloran i tried this on the latest code an works

**Comment by Wholloran** [comment]
There is no longer a "learn more" button on the home/about page (now combined) So closing the ticket.
