### ISSUE TITLE
services/app-developer needs mobile responsive design and code

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/OPENFORGE.IO#270]
![screen shot 2018-11-02 at 11 41 32 am](https://user-images.githubusercontent.com/13290745/47925335-4e00c700-de94-11e8-881e-52638b4d04da.png)
![screen shot 2018-11-02 at 11 41 40 am](https://user-images.githubusercontent.com/13290745/47925336-4e00c700-de94-11e8-9621-e14accb9f80b.png)
![screen shot 2018-11-02 at 11 41 45 am](https://user-images.githubusercontent.com/13290745/47925337-4e00c700-de94-11e8-87dd-65c3c92a41e6.png)

**Comment by Wholloran** [comment]
This should be addressed in one of Sam and Youngs PRs

**Comment by Wholloran** [comment]
new services design resolved this, closing a ticket.
