### ISSUE TITLE
Show us your Skills Slider Handle on Opportunities Page

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#31]
Show us your Skills Slider Handle on Opportunities Page will shrink when you move the slider. Only on Chrome. 

Non-adjusted <img width="863" alt="screen shot 2018-05-17 at 6 40 18 pm" src="https://user-images.githubusercontent.com/37937571/40207343-0a06eb22-5a02-11e8-8c98-84e1dd11c387.png">
Adjusted <img width="830" alt="screen shot 2018-05-17 at 6 40 33 pm" src="https://user-images.githubusercontent.com/37937571/40207347-0cb00b9c-5a02-11e8-80bb-55320009a29d.png">

**Comment by PaulPaulDevelops** [comment]
As a note, this is not a functionality related build instead it is a style that is influencing this. Please check out `-webkit-slider-thumb` when reviewing this issue.

**Comment by Wholloran** [comment]
Slider no longer functions as mentioned in the ticket, so closing the defect
