### ISSUE TITLE
Button that redirect are opening another Tab

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#33]
Pressing the "Get to know us" and "Get in touch" button open the page in a new tab. This is happening in all browsers.

**Comment by PaulPaulDevelops** [comment]
The solution is to remove `target="_blank"` from the link tags to have the redirect not open another tab.

**Comment by Wholloran** [comment]
Clicking the listed button no longer opens a new tab, so closing the ticket
