### ISSUE TITLE
bug-UI(opportunities page - sliders): slider progress color switches sides [IE/Edge]

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#34]
The slider Progress color will switch sides as you move the slider, and the handle for the slider is slightly cut off. This is on Edge and IE

**Comment by PaulPaulDevelops** [comment]
We will need to update the -ms styles within app-slider.css

**Comment by Wholloran** [comment]
WOrking as expected, Closing Ticket.
