### ISSUE TITLE
The text on the "get to know Us" button on the Home page is not centered

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#37]

**Comment by PaulPaulDevelops** [comment]
[Resolved in this commit.](https://github.com/openforge/main-website/commit/a6fd1ad35d02ad19c972aae8387a5f8f43d5a0be) Will update issue once commit is in `develop` branch.

**Comment by Wholloran** [comment]
Text is now centered so closing Ticket
