### ISSUE TITLE
feature(configuration): css linter is not hooked up to ci/cz

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#43]
In this branch I put in linting; but we need to hook it up to our commit process so that npm run cz doesn't go through unless both TS and CSS are properly linted :) 

https://github.com/openforge/main-website/tree/website-server-enhancements

**Comment by Wholloran** [comment]
need to touch base with @LizCottrell about this. I believe we implemented this but it started to break the CSS so it was removed.

**Comment by Wholloran** [comment]
@nbey  I see you referenced a linter. If this ticket can be closed please do so and close the corresponding task(https://openforge.teamwork.com/index.cfm#tasks/10184239)

**Comment by Wholloran** [comment]
A CSS linter is implemented so closing the ticket
