### ISSUE TITLE
Mobile friendly menu pops open randomly when re-sizing the window

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/OPENFORGE.IO#49]
This usually happens when the web-friendly menu switches to the mobile-friendly view of the burger menu. It happens intermittently, but I have noticed that if the web-friendly view is *close* to the mobile-friendly size it will be more likely to happen.

**Comment by PaulPaulDevelops** [comment]
I have been able to re-create this consistently when opening developer tools on Chrome and having the developer tools take up the majority of the screen.
<img width="1430" alt="screen shot 2018-05-23 at 3 55 09 pm" src="https://user-images.githubusercontent.com/13290745/40447809-c5929ea6-5ea1-11e8-81b5-a52132a6c3d7.png">

**Comment by Fdom92** [comment]
@PaulPaulDevelops i was trying to reproduce this issue but i can't see this

**Comment by Wholloran** [comment]
Closing have not seen it in a while
