### ISSUE TITLE
Buttons that navigate to a new page will only load the footer

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#58]
When pressing "get to know us" (Homepage), or "Get in touch"(About Page) they will navigate to the page but display only the footer. All browsers

**Comment by luiskcs89** [comment]
using the stencil-route-link instead of the a tag seems to solve this issue [solved in this commit](https://github.com/openforge/main-website/pull/73/commits/5b39580b574fac98fc045c017c83dfe27ebb0bdb)

**Comment by Wholloran** [comment]
New homepage design no longer navigates to a new page and just scrolls to meet the team. Closing Ticket
