### ISSUE TITLE
Inconsistent issues with Google Chrome

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#59]
When you first navigate to [Website](https://openforge-website-dev.herokuapp.com/) on google chrome the following buttons will not be displayed on the home page ("Let's get started", "Learn about our process" (Both enterprise and startup)). Additionally the button 'Get to Know us" at the bottom of the page will open what seems to be a random page (About, Contact, or opportunities) in another tab. 

Now this new tab that opens seems to function fine(besides #58), and If you navigate back to the home page all the buttons are there and clicking "Get to know us" at the bottom works correctly. 

I will upload quicktime video to slack.

**Comment by Fdom92** [comment]
@Wholloran the buttons seems to be working in the current build

**Comment by Wholloran** [comment]
Have not Come across this all day while testing today. So closing the ticket.
