### ISSUE TITLE
bug(configuration): server css errors

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#61]

**Comment by PaulPaulDevelops** [comment]
@jedihacks could you update the description and provide more information on this issue?

**Comment by jedihacks** [comment]
Sure thing!  

To reproduce on /origin/develop branch; use 'npm start' from terminal.   Then go to your localhost copy, and you should get the following error.

If you refresh/go to other pages; you'll see a couple other errors all relating to CSS & the Hydrator.

<img width="1349" alt="screen shot 2018-05-24 at 4 27 21 pm" src="https://user-images.githubusercontent.com/996175/40512000-79f0b928-5f6f-11e8-8cdf-95ab472893a8.png">

**Comment by jedihacks** [comment]
@luiskcs89

**Comment by luiskcs89** [comment]
I've found that there are some issues in jsdom related to this CSS parsing. The specific case of this screenshoot is due to _last-child_ , but there are also issues when the font-family styles have spaces and so on. Some of the issues seem to be closed for newer versions of jsdom but stencil/core requires 11.5.1 which doesn't have those fixes.

**Comment by jedihacks** [comment]
Is there anything we can do to override the errors for now, or are the errors having any adverse effects?

**Comment by luiskcs89** [comment]
From what I read, the errors don't have an adverse effect on the app, they just come from jsdom's css parser which doesn't support some legitimate CSS features (https://github.com/jsdom/jsdom/issues/2177#issuecomment-376139329). Looks like there is nothing we can do about this from our side.

**Comment by Wholloran** [comment]
Need to update rules for JSdom to silence CSS errors

**Comment by luiskcs89** [comment]
Actually I am not seeing these error logs anymore on the current develop branch and this issue could probably be closed.

**Comment by Wholloran** [comment]
@daftclaud Can you confirm this is resolved on Thursday and If so close the defect.

**Comment by Wholloran** [comment]
Confirmed with Claudio that this can be closed. So Closing ticket

**Comment by daftclaud** [comment]
Just a comment: make sure you run `npm run start` as opposed to just `npm start`
