### ISSUE TITLE
chore(configuration): add config file for language

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#64]

**Comment by PaulPaulDevelops** [comment]
We need to set up a configuration file that contains all the language within the website. That way, if we ever have to update copy or language we only have to do it in a single file. 

This would be similar to how we implement this on previous projects.

**Comment by GroveDev** [comment]
Branch feature/localization is tackling this. Not finished yet though.

**Comment by GroveDev** [comment]
Creation of translationService in every needed component needs to be fixed in some point.

**Comment by Wholloran** [comment]
Confirmed with Nafis that this can be closed. so closing the ticket.
