### ISSUE TITLE
feature(case studies page): design + configure file hosting

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#67]

**Comment by PaulPaulDevelops** [comment]
The goal is to be able to host our designs as a case study on the website. We will need a design for this portion of how the user will navigate to the case study .. it being on the blog, or a separate page itself.
We will need to look into how to host these files.

**Comment by Wholloran** [comment]
The issue Is backlogged, Updated conversation to teamwork Task, Closing the issue.
