### ISSUE TITLE
feature(configuration): lazy loading images

### ISSUE THREAD

**Issue by Fdom92** [openforge/OPENFORGE.IO#68]
I think we should be using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to add some lazy loading to the img that are not displayed in the first paint, so we don't need to load them.

There is an example on how to use it to lazy load img from Justin (ionic team member) [here](https://github.com/jgw96/st-img)

**Comment by Fdom92** [comment]
This is fixed with this PR https://github.com/openforge/OPENFORGE.IO/pull/79

**Comment by Wholloran** [comment]
As per today's meetings, lazy loading needs to be added to the remainder of the images on the site.
