### ISSUE TITLE
feature(global - hero backgrounds): add parallax to hero background images

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#69]
Add parallax animation to all hero background images.  Must consult with design to acquire image assets and receive animation approval.

**Expected Result:**
As the user scrolls down the page, the hero background images shall have a subtle animation. See: https://medium.com/@hamstu/recreating-the-firewatch-parallax-effect-213694d42f4e

**Comment by PaulPaulDevelops** [comment]
This is the same as #62 so closing this issue.

**Comment by Wholloran** [comment]
THe issue is backlogged, Updated message history to teamwork task and closing the ticket.
