### ISSUE TITLE
feature(spa + seo): structured data

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#74]
Single Page Web apps (SPA's) have certain configurations that need to be performed in order to properly index data for Google's crawler.

One of those pieces is Structured Data, which is described here:  https://developers.google.com/search/docs/guides/intro-structured-data?visit_id=1-636631240128162327-3698134189&hl=en&rd=1

I've created two property listings on Search Console, and added Billy, Geoff, Paulina, and Luis to the listing.

https://www.google.com/webmasters/tools/dashboard?siteUrl=http://www.openforge.io/

Whoever takes this task, please do the following:

1.  Research structured data and the links above
2. Create proposed data structure for our pages.  Feel free to bring someone in to pair program with you.
3.  Add me as a reviewer when it's ready for code review or when you need keywords.

**Comment by PaulPaulDevelops** [comment]
The initial structured data is causing an issue on `develop` when running `npm start`. The error is copied down below -

> [06:40.1]  prerendering failed in 1.49 s
[06:40.1]  inject manifest into service worker finished in 711 ms
> [ ERROR ]  Minify JS
           Unexpected token: punc (:)
> [06:40.1]
 build failed in 12.01 s

**Comment by Wholloran** [comment]
Closing the ticket, after next iteration of changes are made I will rerun lighthouse and open a new ticket if needed.
