### ISSUE TITLE
feature(spa + seo): prerender

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#76]
Prerender our SPA so that the entire application is crawl-able by search engines, including HTML.

https://prerender.io/

**Comment by mmalcorn** [comment]
Stencil is already prerendering for us, and is crawlable
https://stenciljs.com/docs/prerendering

Wondering if there were any other advantages or reasons for using prerender.io. Pausing this task for now.

**Comment by Wholloran** [comment]
Confirmed with Paulina that this can be closed, will be having Geoff trigger a crawl from google
