### ISSUE TITLE
External links accessible

### ISSUE THREAD

**Issue by Fdom92** [openforge/OPENFORGE.IO#88]
We should improve the accessibility on our external links like this [doc](https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse) mention.

>  Link text (and alternate text for images, when used as links) must be discernible by a screen reader, must not have a duplicate label, and must be focusable.

**Comment by Fdom92** [comment]
This is fixed in this PR https://github.com/openforge/OPENFORGE.IO/pull/89

**Comment by Wholloran** [comment]
I am able to tab to all links and accessibility is coming back as 91% on lighthouse. Closing Ticket.
