### ISSUE TITLE
Provide fallback content when JavaScript is not available

### ISSUE THREAD

**Issue by Fdom92** [openforge/OPENFORGE.IO#90]
We should provide just a message in case JavaScript is not available, this also will improve our score in lighthouse.

More doc [here](https://developers.google.com/web/tools/lighthouse/audits/no-js)

**Comment by Fdom92** [comment]
This is fixed in this PR https://github.com/openforge/OPENFORGE.IO/pull/91

**Comment by Wholloran** [comment]
Closing
