### ISSUE TITLE
Assets not loading on production

### ISSUE THREAD

**Issue by Fdom92** [openforge/OPENFORGE.IO#92]

**Comment by Fdom92** [comment]
This is fixed in this PR https://github.com/openforge/OPENFORGE.IO/pull/93

**Comment by Wholloran** [comment]
The backend and buttons that were not loading before are now loading for me, @Fdom92  if all assets you noticed that was missing when you opened the ticket are now present you can Close this ticket.

**Comment by Wholloran** [comment]
paulina says CLOSED
