### ISSUE TITLE
Ionic/React Links not opening in a new tab

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#94]
The Ionic/React Links on the opportunities page are not opening in a new tab, they redirect the current tab to that URL.

**Comment by PaulPaulDevelops** [comment]
This is resolve within PR #87, please re-test with the latest `develop`

**Comment by Wholloran** [comment]
Running on the latest version of dev they still are not opening in a new tab @PaulPaulDevelops

**Comment by Wholloran** [comment]
URLs are opening in a new tab, Closing the ticket.
