### ISSUE TITLE
bug(global - tablet/mobile): hamburger menu does not open on-click/on-touch

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#96]
**Environment:**
 Production 6-11-18

**Steps to Recreate:**
Navigate to openforge.io on any viewport smaller than 992px wide

**Expected Result:**
Hamburger menu opens on-click or on-touch (on devices)

**Actual Result:**
Hamburger menu does not open on-click or on-touch (on devices)

**Comment by nbey** [comment]
This has been resolved in commit https://github.com/openforge/OPENFORGE.IO/commit/8ce0d02db8411cd3f840d453320404b6ac33d9d8

@PaulPaulDevelops 
Should I create a PR for `bug-fixes` -> `develop`?
