### ISSUE TITLE
"get To know Us" button does Nothing

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#99]
"get To know Us" button does Nothing. When you click is it changes the URL to "....../#learnabout" and throws this error. 
![screen shot 2018-05-30 at 2 16 59 pm](https://user-images.githubusercontent.com/37937571/40739441-334249ca-6414-11e8-9d7e-01fd1b701cb4.png)

**Comment by PaulPaulDevelops** [comment]
Fixed within this [commit ](https://github.com/openforge/OPENFORGE.IO/commit/0eaf19821d264a227d0898dd3690984c7ce7c0d5)

**Comment by Wholloran** [comment]
Button is now functioning, Closing Ticket
